import type {
  ActivityBand,
  Category,
  EvidenceSource,
  Methodology,
  Platform,
  PnlBucket,
  ProfitabilityStat,
  SurvivorBand,
  TimeSeriesPoint,
  Timeframe,
  WalletCounts,
} from "@/lib/types";

/**
 * DEMO DATASET -- synthetic records for interface development only.
 *
 * Section 44 of the build spec allows mock data during development provided it
 * is visibly labelled. Every record below carries `isDemo: true`, which drives
 * the DEMO DATA banner in the header and a badge on every card and figure.
 *
 * These numbers are generated by the helper at the bottom of this file. They
 * are NOT measurements of the named platforms, and no real Dune query, dataset
 * or research paper is cited for them -- attaching a real-looking source to a
 * synthetic number is precisely the failure mode this site exists to prevent.
 * Every demo source is marked provider "DEMO", status UNVERIFIED, url null.
 *
 * In production mode (DATA_MODE=production) this file is not loaded at all.
 */

const DEMO_METHODOLOGY = (version: string): Methodology => ({
  pnlDefinition:
    "Realised PnL per wallet: proceeds from closes and sells minus cost basis of opens and buys, in USD at transaction time.",
  feesIncluded: true,
  unrealizedIncluded: false,
  walletClustering: false,
  exclusions: [
    "Wallets with fewer than 2 transactions in the window",
    "Known platform, router and market-maker addresses",
    "Transactions that failed or reverted",
  ],
  filters: ["Window bounded by dataset dates", "USD conversion at block timestamp"],
  dateRangeStart: "2025-01-01",
  dateRangeEnd: "2025-08-15",
  calculationVersion: version,
  notes:
    "Synthetic demonstration record. Not a measurement of the named platform. Present only to exercise the interface.",
});

function demoSources(slug: string): EvidenceSource[] {
  return [
    {
      id: `${slug}-demo-primary`,
      role: "primary",
      provider: "DEMO",
      // Not "onchain-raw": a placeholder must not claim a data class it does
      // not have, or the evidence score credits it +30 for chain data that
      // does not exist.
      type: "aggregator",
      url: null,
      query: `-- DEMO RECORD. This is not a real query and returns no real result.\n-- Replace with a published, re-runnable query before this platform\n-- can leave the review queue.\nSELECT 'insufficient verifiable data' AS status;`,
      datasetDate: "2025-08-15",
      lastVerified: "2025-08-15",
      sampleSize: null,
      reproducible: false,
      status: "UNVERIFIED",
      notes: "Synthetic placeholder. No real dataset is attached to this record.",
    },
  ];
}

interface DemoSpec {
  slug: string;
  name: string;
  category: Category;
  description: string;
  chains: string[];
  website: string | null;
  analyzed: number;
  profitableShare: number;
  breakEvenShare: number;
  unknownShare: number;
  medianPnlUsd: number;
  meanPnlUsd: number;
  topOnePctProfitShare: number;
  /** Profitable share at each activity band, as a multiplier on the baseline. */
  activityDecay: number;
}

/** Deterministic pseudo-random so the demo build is byte-stable. */
function seeded(seed: string): () => number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return () => {
    h += 0x6d2b79f5;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const BUCKET_EDGES: Array<{ min: number | null; max: number | null; label: string }> = [
  { min: null, max: -10_000, label: "< -$10k" },
  { min: -10_000, max: -1_000, label: "-$10k to -$1k" },
  { min: -1_000, max: -100, label: "-$1k to -$100" },
  { min: -100, max: 0, label: "-$100 to $0" },
  { min: 0, max: 100, label: "$0 to $100" },
  { min: 100, max: 1_000, label: "$100 to $1k" },
  { min: 1_000, max: 10_000, label: "$1k to $10k" },
  { min: 10_000, max: null, label: "> $10k" },
];

function buildBuckets(spec: DemoSpec, counts: WalletCounts): PnlBucket[] {
  const rand = seeded(`${spec.slug}-buckets`);
  const losing = counts.unprofitable;
  const winning = counts.profitable;
  // Losses concentrate in the small-loss buckets; wins have a long thin tail.
  const lossWeights = [0.03, 0.14, 0.38, 0.45];
  const winWeights = [0.52, 0.32, 0.13, 0.03];

  const lossCounts = distribute(losing, lossWeights, rand);
  const winCounts = distribute(winning, winWeights, rand);
  const all = [...lossCounts, ...winCounts];

  return BUCKET_EDGES.map((edge, i) => ({ ...edge, wallets: all[i] ?? 0 }));
}

/** Split a total across weights, with the remainder landing on the largest. */
function distribute(total: number, weights: number[], rand: () => number): number[] {
  const jittered = weights.map((w) => w * (0.92 + rand() * 0.16));
  const sum = jittered.reduce((a, b) => a + b, 0);
  const raw = jittered.map((w) => Math.floor((w / sum) * total));
  const remainder = total - raw.reduce((a, b) => a + b, 0);
  const largest = raw.indexOf(Math.max(...raw));
  raw[largest] += remainder;
  return raw;
}

const ACTIVITY_BANDS: Array<{ label: string; minTrades: number; share: number }> = [
  { label: "All wallets", minTrades: 0, share: 1 },
  { label: "10+ trades", minTrades: 10, share: 0.38 },
  { label: "50+ trades", minTrades: 50, share: 0.12 },
  { label: "100+ trades", minTrades: 100, share: 0.055 },
  { label: "500+ trades", minTrades: 500, share: 0.011 },
];

function buildActivityBands(spec: DemoSpec, counts: WalletCounts): ActivityBand[] {
  const baseline = counts.profitable / counts.analyzed;
  return ACTIVITY_BANDS.map((band, i) => {
    const wallets = Math.round(counts.analyzed * band.share);
    const rate = baseline * Math.pow(spec.activityDecay, i);
    return { label: band.label, minTrades: band.minTrades, wallets, profitable: Math.round(wallets * rate) };
  });
}

const SURVIVOR_THRESHOLDS = [1, 100, 1_000, 10_000, 100_000];

function buildSurvivorBands(spec: DemoSpec, counts: WalletCounts, buckets: PnlBucket[]): SurvivorBand[] {
  const above = (threshold: number) =>
    buckets.filter((b) => (b.min ?? -Infinity) >= threshold).reduce((s, b) => s + b.wallets, 0);
  const rand = seeded(`${spec.slug}-survivors`);
  return SURVIVOR_THRESHOLDS.map((threshold) => {
    // Interpolate inside buckets for thresholds that do not land on an edge.
    const exact = above(threshold);
    const scaled = threshold === 1 ? counts.profitable : Math.round(exact * (0.7 + rand() * 0.3));
    return {
      threshold,
      label: threshold === 1 ? "$1+" : `$${threshold.toLocaleString()}+`,
      wallets: Math.min(counts.profitable, scaled),
    };
  });
}

const TIMEFRAME_POINTS: Record<Timeframe, number> = { "7D": 7, "30D": 30, "90D": 12, "1Y": 12, ALL: 18 };

function buildSeries(spec: DemoSpec, counts: WalletCounts): Partial<Record<Timeframe, TimeSeriesPoint[]>> {
  const baseline = (counts.profitable / counts.analyzed) * 100;
  const out: Partial<Record<Timeframe, TimeSeriesPoint[]>> = {};
  (Object.keys(TIMEFRAME_POINTS) as Timeframe[]).forEach((tf) => {
    const rand = seeded(`${spec.slug}-${tf}`);
    const n = TIMEFRAME_POINTS[tf];
    const stepDays = tf === "7D" ? 1 : tf === "30D" ? 1 : tf === "90D" ? 7 : tf === "1Y" ? 30 : 30;
    out[tf] = Array.from({ length: n }, (_, i) => {
      const date = new Date(Date.UTC(2025, 7, 15));
      date.setUTCDate(date.getUTCDate() - (n - 1 - i) * stepDays);
      const drift = (rand() - 0.5) * 3.2;
      return {
        date: date.toISOString().slice(0, 10),
        profitablePct: Number(Math.max(0, baseline + drift).toFixed(2)),
        analyzed: Math.round((counts.analyzed / n) * (0.8 + rand() * 0.4)),
      };
    });
  });
  return out;
}

function buildStat(spec: DemoSpec): ProfitabilityStat {
  const profitable = Math.round(spec.analyzed * spec.profitableShare);
  const breakEven = Math.round(spec.analyzed * spec.breakEvenShare);
  const unknown = Math.round(spec.analyzed * spec.unknownShare);
  const counts: WalletCounts = {
    analyzed: spec.analyzed,
    profitable,
    breakEven,
    unknown,
    unprofitable: spec.analyzed - profitable - breakEven - unknown,
  };
  const buckets = buildBuckets(spec, counts);
  return {
    counts,
    medianPnlUsd: spec.medianPnlUsd,
    meanPnlUsd: spec.meanPnlUsd,
    topOnePctProfitShare: spec.topOnePctProfitShare,
    buckets,
    activityBands: buildActivityBands(spec, counts),
    survivorBands: buildSurvivorBands(spec, counts, buckets),
    series: buildSeries(spec, counts),
    methodology: DEMO_METHODOLOGY("demo-v1"),
    sources: demoSources(spec.slug),
    // Demo records never claim strong evidence. The score computes low, which
    // is the honest result for a record with no reproducible source.
    evidenceFactors: {
      officialOrRawChainData: false,
      publicReproducibleSql: false,
      methodologyDisclosed: true,
      largeSample: spec.analyzed >= 100_000,
      recentData: false,
      independentSecondSource: false,
    },
    periodStart: "2025-01-01",
    periodEnd: "2025-08-15",
    lastUpdated: "2025-08-15T00:00:00.000Z",
  };
}

const DEMO_SPECS: DemoSpec[] = [
  {
    slug: "pump-fun",
    name: "Pump.fun",
    category: "memecoins",
    description: "Solana memecoin launchpad using a bonding curve that graduates tokens to an AMM.",
    chains: ["Solana"],
    website: "https://pump.fun",
    analyzed: 1_842_000,
    profitableShare: 0.031,
    breakEvenShare: 0.014,
    unknownShare: 0.006,
    medianPnlUsd: -38,
    meanPnlUsd: -11,
    topOnePctProfitShare: 0.71,
    activityDecay: 0.86,
  },
  {
    slug: "hyperliquid",
    name: "Hyperliquid",
    category: "perps",
    description: "Perpetual futures exchange running on its own L1 with a fully on-chain order book.",
    chains: ["Hyperliquid L1"],
    website: "https://hyperliquid.xyz",
    analyzed: 412_500,
    profitableShare: 0.187,
    breakEvenShare: 0.021,
    unknownShare: 0.008,
    medianPnlUsd: -212,
    meanPnlUsd: 43,
    topOnePctProfitShare: 0.64,
    activityDecay: 0.94,
  },
  {
    slug: "jupiter-perps",
    name: "Jupiter Perps",
    category: "perps",
    description: "Solana perpetuals venue where traders take leverage against a shared liquidity pool.",
    chains: ["Solana"],
    website: "https://jup.ag",
    analyzed: 268_900,
    profitableShare: 0.163,
    breakEvenShare: 0.019,
    unknownShare: 0.011,
    medianPnlUsd: -178,
    meanPnlUsd: -22,
    topOnePctProfitShare: 0.58,
    activityDecay: 0.92,
  },
  {
    slug: "gmx",
    name: "GMX",
    category: "perps",
    description: "Perpetual exchange on Arbitrum and Avalanche using a multi-asset liquidity pool.",
    chains: ["Arbitrum", "Avalanche"],
    website: "https://gmx.io",
    analyzed: 148_300,
    profitableShare: 0.212,
    breakEvenShare: 0.024,
    unknownShare: 0.009,
    medianPnlUsd: -96,
    meanPnlUsd: 18,
    topOnePctProfitShare: 0.52,
    activityDecay: 0.95,
  },
  {
    slug: "kalshi",
    name: "Kalshi",
    category: "prediction-markets",
    description: "CFTC-regulated US event contract exchange offering binary event markets.",
    chains: [],
    website: "https://kalshi.com",
    analyzed: 96_400,
    profitableShare: 0.318,
    breakEvenShare: 0.048,
    unknownShare: 0.012,
    medianPnlUsd: -24,
    meanPnlUsd: -6,
    topOnePctProfitShare: 0.41,
    activityDecay: 0.97,
  },
  {
    slug: "limitless",
    name: "Limitless",
    category: "prediction-markets",
    description: "On-chain prediction market on Base focused on short-duration event contracts.",
    chains: ["Base"],
    website: "https://limitless.exchange",
    analyzed: 42_100,
    profitableShare: 0.284,
    breakEvenShare: 0.037,
    unknownShare: 0.014,
    medianPnlUsd: -31,
    meanPnlUsd: -9,
    topOnePctProfitShare: 0.47,
    activityDecay: 0.96,
  },
  {
    slug: "letsbonk",
    name: "LetsBonk",
    category: "memecoins",
    description: "Solana memecoin launchpad in the Bonk ecosystem using a bonding-curve launch model.",
    chains: ["Solana"],
    website: null,
    analyzed: 386_700,
    profitableShare: 0.042,
    breakEvenShare: 0.016,
    unknownShare: 0.007,
    medianPnlUsd: -29,
    meanPnlUsd: -8,
    topOnePctProfitShare: 0.68,
    activityDecay: 0.88,
  },
  {
    slug: "four-meme",
    name: "Four.meme",
    category: "memecoins",
    description: "BNB Chain token launch platform using a bonding curve before AMM migration.",
    chains: ["BNB Chain"],
    website: null,
    analyzed: 214_800,
    profitableShare: 0.038,
    breakEvenShare: 0.015,
    unknownShare: 0.009,
    medianPnlUsd: -33,
    meanPnlUsd: -10,
    topOnePctProfitShare: 0.66,
    activityDecay: 0.87,
  },
];

/**
 * Platforms with no verifiable participant-level data.
 *
 * These are NOT demo records -- the statement "this is not published" is a
 * factual claim about data availability that holds in demo and production
 * alike. Centralized casinos publish house-edge and volume figures, not
 * per-user outcomes, and house edge is not observed trader profitability.
 */
const UNKNOWN_PLATFORMS: Platform[] = [
  {
    slug: "rollbit",
    name: "Rollbit",
    category: "casinos",
    description: "Centralized crypto casino and sportsbook with an in-house token and trading products.",
    chains: [],
    website: "https://rollbit.com",
    stat: null,
    unknownReason: "centralized-no-participant-data",
    dataAvailabilityNote:
      "Available: aggregate wagered volume and marketing figures published by the operator, plus on-chain movement of the platform's own token. Not available: per-user deposit, withdrawal or net-result data. Nothing public supports a participant profitability rate, and the published house edge is a property of the games, not a measurement of what users finished with.",
    isDemo: false,
  },
  {
    slug: "stake",
    name: "Stake",
    category: "casinos",
    description: "Centralized crypto casino and sportsbook operating across multiple jurisdictions.",
    chains: [],
    website: "https://stake.com",
    stat: null,
    unknownReason: "centralized-no-participant-data",
    dataAvailabilityNote:
      "Available: hot-wallet flows observable on chain and operator-published volume claims. Not available: per-account results, which are held in the operator's internal ledger. Wallet flows show gross movement between the platform and users, not who ended ahead.",
    isDemo: false,
  },
  {
    slug: "shuffle",
    name: "Shuffle",
    category: "casinos",
    description: "Centralized crypto casino with a token-based loyalty programme.",
    chains: [],
    website: "https://shuffle.com",
    stat: null,
    unknownReason: "centralized-no-participant-data",
    dataAvailabilityNote:
      "Available: on-chain deposit and withdrawal addresses, plus operator volume claims. Not available: per-user net results. No public dataset supports a participant profitability percentage.",
    isDemo: false,
  },
  {
    slug: "bc-game",
    name: "BC.Game",
    category: "casinos",
    description: "Centralized crypto casino offering in-house and third-party game titles.",
    chains: [],
    website: "https://bc.game",
    stat: null,
    unknownReason: "centralized-no-participant-data",
    dataAvailabilityNote:
      "Available: exchange-style wallet flows and operator marketing figures. Not available: account-level outcomes. Any profitability rate quoted for this platform would be manufactured.",
    isDemo: false,
  },
  {
    slug: "drift",
    name: "Drift",
    category: "perps",
    description: "Solana perpetuals exchange with an on-chain order book and prediction market products.",
    chains: ["Solana"],
    website: "https://drift.trade",
    stat: null,
    unknownReason: "research-pending",
    dataAvailabilityNote:
      "Trades settle on chain and are readable, so a wallet-level profitability figure is computable in principle. It is not published here because the query has not been written, reviewed and reproduced yet. Listed so the gap is visible rather than hidden.",
    isDemo: false,
  },
  {
    slug: "dydx",
    name: "dYdX",
    category: "perps",
    description: "Perpetual futures exchange running on its own Cosmos-based chain.",
    chains: ["dYdX Chain"],
    website: "https://dydx.exchange",
    stat: null,
    unknownReason: "research-pending",
    dataAvailabilityNote:
      "Fills are recorded on the dYdX chain and an indexer API is public, so a reproducible figure is achievable. No reviewed query exists yet, so no number is shown.",
    isDemo: false,
  },
];

export function demoPlatforms(): Platform[] {
  const generated: Platform[] = DEMO_SPECS.map((spec) => ({
    slug: spec.slug,
    name: spec.name,
    category: spec.category,
    description: spec.description,
    chains: spec.chains,
    website: spec.website,
    stat: buildStat(spec),
    unknownReason: null,
    dataAvailabilityNote: null,
    isDemo: true,
  }));
  return [...generated, ...UNKNOWN_PLATFORMS];
}
